export const allConsejos = [
  { text: 'Bebe agua cada 2 horas para mantenerte hidratado 💧' },
  { text: 'Camina al menos 20 minutos hoy para mantener tu salud activa 🚶‍♂️' },
  { text: 'Haz una pausa para sonreír y contagiar alegría 😄' },
  { text: 'Lee al menos 10 páginas de un libro hoy 📚' },
  { text: 'Respira profundamente durante 1 minuto para relajarte 🌬️' },
  { text: 'Organiza tu espacio de trabajo para mayor productividad 🧹' },
  { text: 'Escucha tu canción favorita para mejorar tu ánimo 🎶' },
  { text: 'Escribe tres cosas por las que estás agradecido hoy ✍️' },
  { text: 'Desconéctate de las redes sociales por una hora 📵' },
  { text: 'Haz una lista de tareas para organizar tu día 📝' },
  { text: 'Sal a tomar un poco de sol para obtener vitamina D ☀️' },
  { text: 'Llama a un amigo o familiar para saludarlo 📞' },
  { text: 'Haz estiramientos al despertar para activar tu cuerpo 🤸‍♂️' },
  { text: 'Prepara una comida saludable y disfrútala 🥗' },
  { text: 'Dedica 5 minutos a meditar y calmar tu mente 🧘‍♂️' },
  { text: 'Ayuda a alguien sin esperar nada a cambio 🤝' },
  { text: 'Evita el consumo excesivo de azúcar hoy 🍬' },
  { text: 'Duerme al menos 7 horas para descansar bien 🛌' },
  { text: 'Aprende una palabra nueva en otro idioma 🌎' },
  { text: 'Haz una caminata corta después de comer 🚶‍♀️' },
  { text: 'Escucha atentamente a los demás cuando hablen 👂' },
  { text: 'Haz una pausa para mirar por la ventana y relajarte 🌳' },
  { text: 'Evita multitareas, concéntrate en una cosa a la vez 🎯' },
  { text: 'Haz un acto de bondad al azar hoy 💖' },
  { text: 'Desayuna bien para empezar el día con energía 🍳' },
  { text: 'Haz una lista de tus metas para la semana 📆' },
  { text: 'Tómate un momento para cuidar una planta 🌱' },
  { text: 'Evita pantallas al menos 30 minutos antes de dormir 📵' },
  { text: 'Haz una pausa para estirarte cada hora ⏰' },
  { text: 'Escucha un podcast interesante 🎧' },
  { text: 'Haz una limpieza rápida de tu correo electrónico 📧' },
  { text: 'Dedica tiempo a tu pasatiempo favorito 🎨' },
  { text: 'Haz una caminata consciente, prestando atención a tu entorno 🚶' },
  { text: 'Prepara una infusión o té relajante 🍵' },
  { text: 'Haz una lista de cosas que te hacen feliz 😊' },
  { text: 'Evita quejarte durante todo el día 🚫' },
  { text: 'Haz una pausa para agradecer lo que tienes 🙏' },
  { text: 'Lee una noticia positiva hoy 📰' },
  { text: 'Haz un dibujo, aunque sea sencillo ✏️' },
  { text: 'Dedica tiempo a escuchar música relajante 🎼' },
  { text: 'Haz una pausa para cuidar tu postura 🪑' },
  { text: 'Evita bebidas azucaradas hoy 🥤' },
  { text: 'Haz una caminata descalzo sobre césped si puedes 🌿' },
  { text: 'Prepara una comida casera y compártela 🍲' },
  { text: 'Haz una pausa para observar el cielo ☁️' },
  { text: 'Escribe una carta o mensaje a alguien especial 💌' },
  { text: 'Haz una lista de tus logros recientes 🏆' },
  { text: 'Dedica tiempo a planear tu próximo descanso 🏖️' },
  { text: 'Haz una pausa para hidratar tu piel 🧴' },
  { text: 'Evita el uso excesivo del celular hoy 📱' },
  { text: 'Haz una pausa para escuchar los sonidos a tu alrededor 👂' },
  { text: 'Haz una lista de cosas que quieres aprender 🧠' },
  { text: 'Dedica tiempo a ordenar tus archivos digitales 💻' },
  { text: 'Haz una pausa para respirar aire fresco 🌬️' },
  { text: 'Evita comer frente a una pantalla 🍽️' },
  { text: 'Haz una pausa para agradecer a alguien hoy 🙌' },
  { text: 'Haz una lista de tus fortalezas personales 💪' },
  { text: 'Dedica tiempo a cuidar tu salud mental 🧠' },
  { text: 'Haz una pausa para abrazar a alguien 🤗' },
  { text: 'Evita pensamientos negativos, reemplázalos por positivos 🌈' },
  { text: 'Haz una pausa para escuchar tu canción favorita 🎵' },
  { text: 'Haz una lista de lugares que te gustaría visitar 🌍' },
  { text: 'Dedica tiempo a aprender algo nuevo hoy 📖' },
  { text: 'Haz una pausa para mirar fotos que te hagan feliz 🖼️' },
  { text: 'Evita el estrés, respira y relájate 🧘' },
  { text: 'Haz una pausa para escribir tus pensamientos 📝' },
  { text: 'Haz una lista de tus sueños y aspiraciones ✨' },
  { text: 'Dedica tiempo a cuidar tu higiene personal 🛁' },
  { text: 'Haz una pausa para disfrutar de un momento de silencio 🤫' },
  { text: 'Evita la procrastinación, haz una tarea pendiente ahora ⏳' },
  { text: 'Haz una pausa para agradecer el día de hoy 🌅' },
  { text: 'Haz una lista de tus películas favoritas 🎬' },
  { text: 'Dedica tiempo a jugar o divertirte 🎲' },
  { text: 'Haz una pausa para observar la naturaleza 🌺' },
  { text: 'Evita discusiones innecesarias hoy 🕊️' },
  { text: 'Haz una pausa para cuidar tu alimentación 🥦' },
  { text: 'Haz una lista de tus canciones favoritas 🎶' },
  { text: 'Dedica tiempo a reflexionar sobre tus logros 🏅' },
  { text: 'Haz una pausa para cuidar tu espalda 🧍‍♂️' },
  { text: 'Evita el exceso de cafeína hoy ☕' },
  { text: 'Haz una pausa para mirar una película o serie 🎥' },
  { text: 'Haz una lista de cosas que quieres regalar 🎁' },
  { text: 'Dedica tiempo a limpiar tu espacio personal 🧽' },
  { text: 'Haz una pausa para mirar el atardecer 🌇' },
  { text: 'Evita el ruido excesivo, busca tranquilidad 🔇' },
  { text: 'Haz una pausa para cuidar tu vista 👀' },
  { text: 'Haz una lista de tus libros favoritos 📚' },
  { text: 'Dedica tiempo a escribir un diario personal 📔' },
  { text: 'Haz una pausa para escuchar el canto de los pájaros 🐦' },
  { text: 'Evita el desorden, organiza tu espacio 🗂️' },
  { text: 'Haz una pausa para agradecer a tu cuerpo por todo lo que hace 🧍' },
  { text: 'Haz una lista de tus metas a corto plazo 🎯' },
  { text: 'Dedica tiempo a aprender una habilidad nueva 🛠️' },
  { text: 'Haz una pausa para disfrutar de un postre 🍰' },
  { text: 'Evita la comparación con los demás, valora tu propio camino 🛤️' },
  { text: 'Haz una pausa para recordar un buen momento del pasado 🕰️' },
  { text: 'Haz una lista de cosas que quieres mejorar 🛠️' },
  { text: 'Dedica tiempo a cuidar tu salud física 🏋️‍♂️' },
  { text: 'Haz una pausa para agradecer a tus seres queridos ❤️' },
  { text: 'Haz una lista de tus comidas favoritas 🍲' },
  { text: 'Dedica tiempo a descansar y recargar energías 🔋' },
  { text: 'Haz una pausa para mirar las estrellas ✨' },
];
